### PR TITLE
Simplify NameConverter and make it more generic

### PR DESCRIPTION
**Pull request by henrikbulldog**

### CODE REVIEW

**Review by Rajesh2015 — CHANGES_REQUESTED** [review]
We should remove 
libraryDependencies += "org.scalaj" %% "scalaj-http" % "2.4.2" dependency as we removed webnamedatabase and we donot rely on this library  anymore

**Review by Rajesh2015 — APPROVED** [review]
lgtm

**Comment by henrikbulldog** [comment]
> We should remove
> libraryDependencies += "org.scalaj" %% "scalaj-http" % "2.4.2" dependency as we removed webnamedatabase and we donot rely on this library anymore

Done

**Comment by henrikbulldog** [comment]
Stick with WebNameDatabase, it seems quite useful

**Pull request closed without merging**
